### ISSUE TITLE
Broken aspect ratio and not an animation

### ISSUE THREAD

**Issue by kellixon** [F32Organization/Faithful32-1.12.2#77]
`[11:16:13] [Client thread/ERROR] [net.minecraft.client.renderer.texture.TextureMap]: Unable to parse metadata from biomesoplenty:textures/blocks/cloverstem.png
java.lang.RuntimeException: broken aspect ratio and not an animation
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.loadSprite(TextureAtlasSprite.java:380) ~[cdq.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.loadTextureAtlas(TextureMap.java:238) [cdp.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.loadSprites(TextureMap.java:155) [cdp.class:?]
	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:159) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:513) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3931) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by kellixon** [comment]
That is all right!

**Comment by StefanTT** [comment]
Thanks for reporting and testing!
